export const ANALYTICS_EVENTS = {
  ONBOARDING_INFO_PAGE_VIEWED: 'Onboarding - Info Page Viewed',
  ONBOARDING_INFO_CONTINUE_CLICKED: 'Onboarding - Info Continue Clicked',
  ONBOARDING_TERMS_PAGE_VIEWED: 'Onboarding - Terms Page Viewed',
  ONBOARDING_TERMS_ACCEPTED: 'Onboarding - Terms Accepted',
  ONBOARDING_PASSWORD_PAGE_VIEWED: 'Onboarding - Password Page Viewed',
  ONBOARDING_PASSWORD_SET: 'Onboarding - Password Set',
  ONBOARDING_EMAIL_PAGE_VIEWED: 'Onboarding - Email Page Viewed',
  ONBOARDING_EMAIL_AUTHENTICATED: 'Onboarding - Email Authenticated',
  ONBOARDING_CARD_AUTHENTICATED: 'Onboarding - Card Authenticated',
  ONBOARDING_COMPLETED: 'Onboarding - Completed',
  ONBOARDING_CANCELLED: 'Onboarding - Cancelled',

  SEND_FLOW_STARTED: 'Send - Flow Started',
  SEND_VIEWED_SUMMARY: 'Send - Viewed Summary',
  SEND_ATTEMPTED_SIGNING: 'Send - Attempted Signing',
  SEND_SUCCEEDED: 'Send - Succeeded',
  SEND_FAILED: 'Send - Failed',
  SEND_CANCELLED: 'Send - Cancelled',
  SEND_DEVICE_ACTION_STARTED: 'Send - Device Action Started',

  RECEIVE_FLOW_STARTED: 'Receive - Flow Started',
  RECEIVE_ADDRESS_VERIFIED_ON_DEVICE: 'Receive - Address Verified on Device',
  RECEIVE_SKIPPED_VERIFICATION: 'Receive - Skipped Verification',
  RECEIVE_SUCCEEDED: 'Receive - Succeeded',
  RECEIVE_CANCELLED: 'Receive - Cancelled',
  RECEIVE_DEVICE_ACTION_STARTED: 'Receive - Device Action Started',
  RECEIVE_DEVICE_ACTION_COMPLETED: 'Receive - Device Action Completed',
  RECEIVE_RETRY_ACTION: 'Receive - Retry Action',
  RECEIVE_CONTINUE_ACTION: 'Receive - Continue Action',

  SWAP_FLOW_STARTED: 'Swap - Flow Started',
  SWAP_QUOTES_REQUESTED: 'Swap - Quotes Requested',
  SWAP_QUOTES_RECEIVED: 'Swap - Quotes Received',
  SWAP_PROVIDER_SELECTED: 'Swap - Provider Selected',
  SWAP_VIEWED_SUMMARY: 'Swap - Viewed Summary',
  SWAP_RECEIVE_STEP_STARTED: 'Swap - Receive Step Started',
  SWAP_SEND_STEP_STARTED: 'Swap - Send Step Started',
  SWAP_SUCCEEDED: 'Swap - Succeeded',
  SWAP_FAILED: 'Swap - Failed',
  SWAP_CANCELLED: 'Swap - Cancelled',
  SWAP_DIRECTION_SWAPPED: 'Swap - Direction Swapped',
  SWAP_DIALOG_CLOSED: 'Swap - Dialog Closed',

  BUY_CRYPTO_FLOW_STARTED: 'Buy Crypto - Flow Started',
  BUY_CRYPTO_CURRENCY_PAGE_VIEWED: 'Buy Crypto - Currency Page Viewed',
  BUY_CRYPTO_FIAT_CURRENCY_SELECTED: 'Buy Crypto - Fiat Currency Selected',
  BUY_CRYPTO_CRYPTO_CURRENCY_SELECTED: 'Buy Crypto - Crypto Currency Selected',
  BUY_CRYPTO_AMOUNT_ENTERED: 'Buy Crypto - Amount Entered',
  BUY_CRYPTO_CONTINUE_TO_ACCOUNT: 'Buy Crypto - Continue to Account',
  BUY_CRYPTO_ACCOUNT_PAGE_VIEWED: 'Buy Crypto - Account Page Viewed',
  BUY_CRYPTO_WALLET_SELECTED: 'Buy Crypto - Wallet Selected',
  BUY_CRYPTO_ACCOUNT_SELECTED: 'Buy Crypto - Account Selected',
  BUY_CRYPTO_PAYMENT_METHOD_SELECTED: 'Buy Crypto - Payment Method Selected',
  BUY_CRYPTO_CONTINUE_TO_ORDER: 'Buy Crypto - Continue to Order',
  BUY_CRYPTO_ORDER_PAGE_VIEWED: 'Buy Crypto - Order Page Viewed',
  BUY_CRYPTO_ORDER_INITIATED: 'Buy Crypto - Order Initiated',
  BUY_CRYPTO_ORDER_COMPLETED: 'Buy Crypto - Order Completed',
  BUY_CRYPTO_ORDER_CANCELLED: 'Buy Crypto - Order Cancelled',
  BUY_CRYPTO_BACK_NAVIGATION: 'Buy Crypto - Back Navigation',
  BUY_CRYPTO_RETRY_ATTEMPT: 'Buy Crypto - Retry Attempt',

  PORTFOLIO_PAGE_VIEWED: 'Portfolio - Page Viewed',
  PORTFOLIO_WALLET_SELECTED: 'Portfolio - Wallet Selected',
  PORTFOLIO_ASSET_CLICKED: 'Portfolio - Asset Clicked',
  PORTFOLIO_ADD_ACCOUNT_CLICKED: 'Portfolio - Add Account Clicked',

  WALLET_PAGE_VIEWED: 'Wallet - Page Viewed',
  WALLET_WALLET_SELECTED: 'Wallet - Wallet Selected',
  WALLET_ACCOUNT_CLICKED: 'Wallet - Account Clicked',
  WALLET_TOKEN_CLICKED: 'Wallet - Token Clicked',
  WALLET_ADD_ACCOUNT_CLICKED: 'Wallet - Add Account Clicked',
  WALLET_ADD_TOKEN_CLICKED: 'Wallet - Add Token Clicked',
  WALLET_ACCOUNT_STATUS_CLICKED: 'Wallet - Account Status Clicked',
  WALLET_SORT_CHANGED: 'Wallet - Sort Changed',
  WALLET_SEARCH_USED: 'Wallet - Search Used',

  INHERITANCE_SETUP_PAGE_VIEWED: 'Inheritance - Setup Page Viewed',
  INHERITANCE_SETUP_COVER_CLICKED: 'Inheritance - Setup Cover Clicked',
  INHERITANCE_SYNC_MAIL_CLICKED: 'Inheritance - Sync Mail Clicked',
  INHERITANCE_LEARN_MORE_CLICKED: 'Inheritance - Learn More Clicked',
  INHERITANCE_SILVER_PLAN_CLICKED: 'Inheritance - Silver Plan Clicked',
  INHERITANCE_GOLD_PLAN_CLICKED: 'Inheritance - Gold Plan Clicked',

  SYNC_ACCOUNTS: 'Sync - Accounts',
  SYNC_INHERITANCE_ENABLED: 'Sync - Inheritance Enabled',
} as const;

export type AnalyticsEvent =
  (typeof ANALYTICS_EVENTS)[keyof typeof ANALYTICS_EVENTS];
