export default [
  {
    id: 'ethereum',
    abbr: 'ETH',
    name: 'Ethereum',
    magnitude: 18,
    isTest: false,
    coinGeckoId: 'ethereum',
    coinIndex: '8000003c',
    feesUnit: 'Gwei',
    network: 'main',
    chain: 1,
    color: '#00a6fb',
  },
  {
    id: 'polygon',
    abbr: 'MATIC',
    name: 'Polygon',
    magnitude: 18,
    isTest: false,
    coinGeckoId: 'matic-network',
    coinIndex: '8000003c',
    feesUnit: 'Gwei',
    network: 'polygon',
    chain: 137,
    color: '#8247e5',
  },
  {
    id: 'binance',
    abbr: 'BNB',
    name: 'BNB Smart Chain (BSC)',
    magnitude: 18,
    isTest: false,
    coinGeckoId: 'binancecoin',
    coinIndex: '8000003c',
    feesUnit: 'Gwei',
    network: 'bsc',
    chain: 56,
    color: '#f0b90b',
  },
  {
    id: 'fantom',
    abbr: 'FTM',
    name: 'Fantom Opera',
    magnitude: 18,
    isTest: false,
    coinGeckoId: 'fantom',
    coinIndex: '8000003c',
    feesUnit: 'Gwei',
    network: 'fantom',
    chain: 250,
    color: '#14B5EC',
  },
  {
    id: 'avalanche',
    abbr: 'AVAX',
    name: 'Avalanche (C-Chain)',
    magnitude: 18,
    isTest: false,
    coinGeckoId: 'avalanche-2',
    coinIndex: '8000003c',
    feesUnit: 'nAVAX',
    network: 'avalanche',
    chain: 43114,
    color: '#E84142',
  },
  {
    id: 'optimism',
    abbr: 'ETH',
    name: 'Optimism',
    magnitude: 18,
    isTest: false,
    coinGeckoId: 'ethereum',
    coinIndex: '8000003c',
    feesUnit: 'Gwei',
    network: 'optimism',
    chain: 10,
    color: '#FF0420',
  },
  {
    id: 'arbitrum',
    abbr: 'ETH',
    name: 'Arbitrum One',
    magnitude: 18,
    hasSegwit: false,
    isTest: false,
    coinGeckoId: 'ethereum',
    coinIndex: '8000003c',
    feesUnit: 'Gwei',
    network: 'arbitrum',
    chain: 42161,
    color: '#12AAFF',
  },
];
