export default [
  {
    id: 'bitcoin',
    abbr: 'btc',
    name: 'Bitcoin',
    isTest: false,
    coinGeckoId: 'bitcoin',
    coinIndex: '80000000',
    feesUnit: 'sat/byte',
    supportedAccountTypes: [
      {
        id: 'btc-native-segwit',
        name: 'Native Segwit',
        tag: 'Native Segwit',
        identifier: '0001',
        allowMultiple: true,
      },
      {
        id: 'btc-legacy',
        name: 'Legacy',
        tag: 'Legacy',
        identifier: '0000',
        allowMultiple: true,
      },
    ],
  },
  {
    id: 'litecoin',
    abbr: 'ltc',
    name: 'Litecoin',
    isTest: false,
    coinGeckoId: 'litecoin',
    tokenList: {},
    coinIndex: '80000002',
    feesUnit: 'sat/byte',
    supportedAccountTypes: [],
  },
  {
    id: 'dogecoin',
    abbr: 'doge',
    name: 'Dogecoin',
    isTest: false,
    coinGeckoId: 'dogecoin',
    tokenList: {},
    coinIndex: '80000003',
    feesUnit: 'sat/byte',
    supportedAccountTypes: [],
  },
  {
    id: 'dash',
    abbr: 'dash',
    name: 'Dash',
    isTest: false,
    coinGeckoId: 'dash',
    tokenList: {},
    coinIndex: '80000005',
    feesUnit: 'sat/byte',
    supportedAccountTypes: [],
  },
];
