// Origional data from https://www.iso.org/iso-4217-currency-codes.html
// Modified to include contry details
export default [
  {
    name: 'Afghani',
    code: 'AFN',
    decimals: '2',
    countryName: 'Afghanistan',
    countryCode: 'AF',
    countryFlag: '🇦🇫',
  },
  {
    name: 'Euro',
    code: 'EUR',
    decimals: '2',
    countryName: 'European Union',
    countryCode: 'EU',
    countryFlag: '🇪🇺',
  },
  {
    name: 'Lek',
    code: 'ALL',
    decimals: '2',
    countryName: 'Albania',
    countryCode: 'AL',
    countryFlag: '🇦🇱',
  },
  {
    name: 'Algerian Dinar',
    code: 'DZD',
    decimals: '2',
    countryName: 'Algeria',
    countryCode: 'DZ',
    countryFlag: '🇩🇿',
  },
  {
    name: 'US Dollar',
    code: 'USD',
    decimals: '2',
    countryName: 'United States',
    countryCode: 'US',
    countryFlag: '🇺🇸',
  },
  {
    name: 'Kwanza',
    code: 'AOA',
    decimals: '2',
    countryName: 'Angola',
    countryCode: 'AO',
    countryFlag: '🇦🇴',
  },
  {
    name: 'East Caribbean Dollar',
    code: 'XCD',
    decimals: '2',
    countryName: 'East Caribbean States',
    countryCode: 'EC',
    countryFlag: '🇪🇨',
  },
  {
    name: 'Argentine Peso',
    code: 'ARS',
    decimals: '2',
    countryName: 'Argentina',
    countryCode: 'AR',
    countryFlag: '🇦🇷',
  },
  {
    name: 'Armenian Dram',
    code: 'AMD',
    decimals: '2',
    countryName: 'Armenia',
    countryCode: 'AM',
    countryFlag: '🇦🇲',
  },
  {
    name: 'Aruban Florin',
    code: 'AWG',
    decimals: '2',
    countryName: 'Aruba',
    countryCode: 'AW',
    countryFlag: '🇦🇼',
  },
  {
    name: 'Australian Dollar',
    code: 'AUD',
    decimals: '2',
    countryName: 'Australia',
    countryCode: 'AU',
    countryFlag: '🇦🇺',
  },
  {
    name: 'Azerbaijan Manat',
    code: 'AZN',
    decimals: '2',
    countryName: 'Azerbaijan',
    countryCode: 'AZ',
    countryFlag: '🇦🇿',
  },
  {
    name: 'Bahamian Dollar',
    code: 'BSD',
    decimals: '2',
    countryName: 'Bahamas',
    countryCode: 'BS',
    countryFlag: '🇧🇸',
  },
  {
    name: 'Bahraini Dinar',
    code: 'BHD',
    decimals: '3',
    countryName: 'Bahrain',
    countryCode: 'BH',
    countryFlag: '🇧🇭',
  },
  {
    name: 'Taka',
    code: 'BDT',
    decimals: '2',
    countryName: 'Bangladesh',
    countryCode: 'BD',
    countryFlag: '🇧🇩',
  },
  {
    name: 'Barbados Dollar',
    code: 'BBD',
    decimals: '2',
    countryName: 'Barbados',
    countryCode: 'BB',
    countryFlag: '🇧🇧',
  },
  {
    name: 'Belarusian Ruble',
    code: 'BYN',
    decimals: '2',
    countryName: 'Belarus',
    countryCode: 'BY',
    countryFlag: '🇧🇾',
  },
  {
    name: 'Belize Dollar',
    code: 'BZD',
    decimals: '2',
    countryName: 'Belize',
    countryCode: 'BZ',
    countryFlag: '🇧🇿',
  },
  {
    name: 'CFA Franc BCEAO',
    code: 'XOF',
    decimals: '0',
    countryName: 'West African CFA franc zone',
    countryCode: 'XO',
    countryFlag: '🇽🇴',
  },
  {
    name: 'Bermudian Dollar',
    code: 'BMD',
    decimals: '2',
    countryName: 'Bermuda',
    countryCode: 'BM',
    countryFlag: '🇧🇲',
  },
  {
    name: 'Indian Rupee',
    code: 'INR',
    decimals: '2',
    countryName: 'India',
    countryCode: 'IN',
    countryFlag: '🇮🇳',
  },
  {
    name: 'Ngultrum',
    code: 'BTN',
    decimals: '2',
    countryName: 'Bhutan',
    countryCode: 'BT',
    countryFlag: '🇧🇹',
  },
  {
    name: 'Boliviano',
    code: 'BOB',
    decimals: '2',
    countryName: 'Bolivia',
    countryCode: 'BO',
    countryFlag: '🇧🇴',
  },
  {
    name: 'Mvdol',
    code: 'BOV',
    decimals: '2',
    countryName: 'Bolivia',
    countryCode: 'BO',
    countryFlag: '🇧🇴',
  },
  {
    name: 'Convertible Mark',
    code: 'BAM',
    decimals: '2',
    countryName: 'Bosnia and Herzegovina',
    countryCode: 'BA',
    countryFlag: '🇧🇦',
  },
  {
    name: 'Pula',
    code: 'BWP',
    decimals: '2',
    countryName: 'Botswana',
    countryCode: 'BW',
    countryFlag: '🇧🇼',
  },
  {
    name: 'Norwegian Krone',
    code: 'NOK',
    decimals: '2',
    countryName: 'Norway',
    countryCode: 'NO',
    countryFlag: '🇳🇴',
  },
  {
    name: 'Brazilian Real',
    code: 'BRL',
    decimals: '2',
    countryName: 'Brazil',
    countryCode: 'BR',
    countryFlag: '🇧🇷',
  },
  {
    name: 'Brunei Dollar',
    code: 'BND',
    decimals: '2',
    countryName: 'Brunei',
    countryCode: 'BN',
    countryFlag: '🇧🇳',
  },
  {
    name: 'Bulgarian Lev',
    code: 'BGN',
    decimals: '2',
    countryName: 'Bulgaria',
    countryCode: 'BG',
    countryFlag: '🇧🇬',
  },
  {
    name: 'Burundi Franc',
    code: 'BIF',
    decimals: '0',
    countryName: 'Burundi',
    countryCode: 'BI',
    countryFlag: '🇧🇮',
  },
  {
    name: 'Cabo Verde Escudo',
    code: 'CVE',
    decimals: '2',
    countryName: 'Cabo Verde',
    countryCode: 'CV',
    countryFlag: '🇨🇻',
  },
  {
    name: 'Riel',
    code: 'KHR',
    decimals: '2',
    countryName: 'Cambodia',
    countryCode: 'KH',
    countryFlag: '🇰🇭',
  },
  {
    name: 'CFA Franc BEAC',
    code: 'XAF',
    decimals: '0',
    countryName: 'Central African CFA franc zone',
    countryCode: 'XA',
    countryFlag: '🇽🇦',
  },
  {
    name: 'Canadian Dollar',
    code: 'CAD',
    decimals: '2',
    countryName: 'Canada',
    countryCode: 'CA',
    countryFlag: '🇨🇦',
  },
  {
    name: 'Cayman Islands Dollar',
    code: 'KYD',
    decimals: '2',
    countryName: 'Cayman Islands',
    countryCode: 'KY',
    countryFlag: '🇰🇾',
  },
  {
    name: 'Chilean Peso',
    code: 'CLP',
    decimals: '0',
    countryName: 'Chile',
    countryCode: 'CL',
    countryFlag: '🇨🇱',
  },
  {
    name: 'Unidad de Fomento',
    code: 'CLF',
    decimals: '4',
    countryName: 'Chile',
    countryCode: 'CL',
    countryFlag: '🇨🇱',
  },
  {
    name: 'Yuan Renminbi',
    code: 'CNY',
    decimals: '2',
    countryName: 'China',
    countryCode: 'CN',
    countryFlag: '🇨🇳',
  },
  {
    name: 'Colombian Peso',
    code: 'COP',
    decimals: '2',
    countryName: 'Colombia',
    countryCode: 'CO',
    countryFlag: '🇨🇴',
  },
  {
    name: 'Unidad de Valor Real',
    code: 'COU',
    decimals: '2',
    countryName: 'Colombia',
    countryCode: 'CO',
    countryFlag: '🇨🇴',
  },
  {
    name: 'Comorian Franc',
    code: 'KMF',
    decimals: '0',
    countryName: 'Comoros',
    countryCode: 'KM',
    countryFlag: '🇰🇲',
  },
  {
    name: 'Congolese Franc',
    code: 'CDF',
    decimals: '2',
    countryName: 'Democratic Republic of the Congo',
    countryCode: 'CD',
    countryFlag: '🇨🇩',
  },
  {
    name: 'New Zealand Dollar',
    code: 'NZD',
    decimals: '2',
    countryName: 'New Zealand',
    countryCode: 'NZ',
    countryFlag: '🇳🇿',
  },
  {
    name: 'Costa Rican Colon',
    code: 'CRC',
    decimals: '2',
    countryName: 'Costa Rica',
    countryCode: 'CR',
    countryFlag: '🇨🇷',
  },
  {
    name: 'Cuban Peso',
    code: 'CUP',
    decimals: '2',
    countryName: 'Cuba',
    countryCode: 'CU',
    countryFlag: '🇨🇺',
  },
  {
    name: 'Peso Convertible',
    code: 'CUC',
    decimals: '2',
    countryName: 'Cuba',
    countryCode: 'CU',
    countryFlag: '🇨🇺',
  },
  {
    name: 'Netherlands Antillean Guilder',
    code: 'ANG',
    decimals: '2',
    countryName: 'Curaçao',
    countryCode: 'CW',
    countryFlag: '🇨🇼',
  },
  {
    name: 'Czech Koruna',
    code: 'CZK',
    decimals: '2',
    countryName: 'Czech Republic',
    countryCode: 'CZ',
    countryFlag: '🇨🇿',
  },
  {
    name: 'Danish Krone',
    code: 'DKK',
    decimals: '2',
    countryName: 'Denmark',
    countryCode: 'DK',
    countryFlag: '🇩🇰',
  },
  {
    name: 'Djibouti Franc',
    code: 'DJF',
    decimals: '0',
    countryName: 'Djibouti',
    countryCode: 'DJ',
    countryFlag: '🇩🇯',
  },
  {
    name: 'Dominican Peso',
    code: 'DOP',
    decimals: '2',
    countryName: 'Dominican Republic',
    countryCode: 'DO',
    countryFlag: '🇩🇴',
  },
  {
    name: 'Egyptian Pound',
    code: 'EGP',
    decimals: '2',
    countryName: 'Egypt',
    countryCode: 'EG',
    countryFlag: '🇪🇬',
  },
  {
    name: 'El Salvador Colon',
    code: 'SVC',
    decimals: '2',
    countryName: 'El Salvador',
    countryCode: 'SV',
    countryFlag: '🇸🇻',
  },
  {
    name: 'Nakfa',
    code: 'ERN',
    decimals: '2',
    countryName: 'Eritrea',
    countryCode: 'ER',
    countryFlag: '🇪🇷',
  },
  {
    name: 'Lilangeni',
    code: 'SZL',
    decimals: '2',
    countryName: 'Eswatini',
    countryCode: 'SZ',
    countryFlag: '🇸🇿',
  },
  {
    name: 'Ethiopian Birr',
    code: 'ETB',
    decimals: '2',
    countryName: 'Ethiopia',
    countryCode: 'ET',
    countryFlag: '🇪🇹',
  },
  {
    name: 'Falkland Islands Pound',
    code: 'FKP',
    decimals: '2',
    countryName: 'Falkland Islands',
    countryCode: 'FK',
    countryFlag: '🇫🇰',
  },
  {
    name: 'Fiji Dollar',
    code: 'FJD',
    decimals: '2',
    countryName: 'Fiji',
    countryCode: 'FJ',
    countryFlag: '🇫🇯',
  },
  {
    name: 'CFP Franc',
    code: 'XPF',
    decimals: '0',
    countryName: 'French Polynesia',
    countryCode: 'PF',
    countryFlag: '🇵🇫',
  },
  {
    name: 'Dalasi',
    code: 'GMD',
    decimals: '2',
    countryName: 'Gambia',
    countryCode: 'GM',
    countryFlag: '🇬🇲',
  },
  {
    name: 'Lari',
    code: 'GEL',
    decimals: '2',
    countryName: 'Georgia',
    countryCode: 'GE',
    countryFlag: '🇬🇪',
  },
  {
    name: 'Ghana Cedi',
    code: 'GHS',
    decimals: '2',
    countryName: 'Ghana',
    countryCode: 'GH',
    countryFlag: '🇬🇭',
  },
  {
    name: 'Gibraltar Pound',
    code: 'GIP',
    decimals: '2',
    countryName: 'Gibraltar',
    countryCode: 'GI',
    countryFlag: '🇬🇮',
  },
  {
    name: 'Quetzal',
    code: 'GTQ',
    decimals: '2',
    countryName: 'Guatemala',
    countryCode: 'GT',
    countryFlag: '🇬🇹',
  },
  {
    name: 'Pound Sterling',
    code: 'GBP',
    decimals: '2',
    countryName: 'United Kingdom',
    countryCode: 'GB',
    countryFlag: '🇬🇧',
  },
  {
    name: 'Guinean Franc',
    code: 'GNF',
    decimals: '0',
    countryName: 'Guinea',
    countryCode: 'GN',
    countryFlag: '🇬🇳',
  },
  {
    name: 'Guyana Dollar',
    code: 'GYD',
    decimals: '2',
    countryName: 'Guyana',
    countryCode: 'GY',
    countryFlag: '🇬🇾',
  },
  {
    name: 'Gourde',
    code: 'HTG',
    decimals: '2',
    countryName: 'Haiti',
    countryCode: 'HT',
    countryFlag: '🇭🇹',
  },
  {
    name: 'Lempira',
    code: 'HNL',
    decimals: '2',
    countryName: 'Honduras',
    countryCode: 'HN',
    countryFlag: '🇭🇳',
  },
  {
    name: 'Hong Kong Dollar',
    code: 'HKD',
    decimals: '2',
    countryName: 'Hong Kong',
    countryCode: 'HK',
    countryFlag: '🇭🇰',
  },
  {
    name: 'Forint',
    code: 'HUF',
    decimals: '2',
    countryName: 'Hungary',
    countryCode: 'HU',
    countryFlag: '🇭🇺',
  },
  {
    name: 'Iceland Krona',
    code: 'ISK',
    decimals: '0',
    countryName: 'Iceland',
    countryCode: 'IS',
    countryFlag: '🇮🇸',
  },
  {
    name: 'Rupiah',
    code: 'IDR',
    decimals: '2',
    countryName: 'Indonesia',
    countryCode: 'ID',
    countryFlag: '🇮🇩',
  },
  {
    name: 'SDR (Special Drawing Right)',
    code: 'XDR',
    decimals: '0',
    countryName: 'International Monetary Fund',
    countryCode: 'XD',
    countryFlag: '🌐',
  },
  {
    name: 'Iranian Rial',
    code: 'IRR',
    decimals: '2',
    countryName: 'Iran',
    countryCode: 'IR',
    countryFlag: '🇮🇷',
  },
  {
    name: 'Iraqi Dinar',
    code: 'IQD',
    decimals: '3',
    countryName: 'Iraq',
    countryCode: 'IQ',
    countryFlag: '🇮🇶',
  },
  {
    name: 'New Israeli Sheqel',
    code: 'ILS',
    decimals: '2',
    countryName: 'Israel',
    countryCode: 'IL',
    countryFlag: '🇮🇱',
  },
  {
    name: 'Jamaican Dollar',
    code: 'JMD',
    decimals: '2',
    countryName: 'Jamaica',
    countryCode: 'JM',
    countryFlag: '🇯🇲',
  },
  {
    name: 'Yen',
    code: 'JPY',
    decimals: '0',
    countryName: 'Japan',
    countryCode: 'JP',
    countryFlag: '🇯🇵',
  },
  {
    name: 'Jordanian Dinar',
    code: 'JOD',
    decimals: '3',
    countryName: 'Jordan',
    countryCode: 'JO',
    countryFlag: '🇯🇴',
  },
  {
    name: 'Tenge',
    code: 'KZT',
    decimals: '2',
    countryName: 'Kazakhstan',
    countryCode: 'KZ',
    countryFlag: '🇰🇿',
  },
  {
    name: 'Kenyan Shilling',
    code: 'KES',
    decimals: '2',
    countryName: 'Kenya',
    countryCode: 'KE',
    countryFlag: '🇰🇪',
  },
  {
    name: 'North Korean Won',
    code: 'KPW',
    decimals: '2',
    countryName: 'North Korea',
    countryCode: 'KP',
    countryFlag: '🇰🇵',
  },
  {
    name: 'Won',
    code: 'KRW',
    decimals: '0',
    countryName: 'South Korea',
    countryCode: 'KR',
    countryFlag: '🇰🇷',
  },
  {
    name: 'Kuwaiti Dinar',
    code: 'KWD',
    decimals: '3',
    countryName: 'Kuwait',
    countryCode: 'KW',
    countryFlag: '🇰🇼',
  },
  {
    name: 'Som',
    code: 'KGS',
    decimals: '2',
    countryName: 'Kyrgyzstan',
    countryCode: 'KG',
    countryFlag: '🇰🇬',
  },
  {
    name: 'Lao Kip',
    code: 'LAK',
    decimals: '2',
    countryName: 'Laos',
    countryCode: 'LA',
    countryFlag: '🇱🇦',
  },
  {
    name: 'Lebanese Pound',
    code: 'LBP',
    decimals: '2',
    countryName: 'Lebanon',
    countryCode: 'LB',
    countryFlag: '🇱🇧',
  },
  {
    name: 'Loti',
    code: 'LSL',
    decimals: '2',
    countryName: 'Lesotho',
    countryCode: 'LS',
    countryFlag: '🇱🇸',
  },
  {
    name: 'Rand',
    code: 'ZAR',
    decimals: '2',
    countryName: 'South Africa',
    countryCode: 'ZA',
    countryFlag: '🇿🇦',
  },
  {
    name: 'Liberian Dollar',
    code: 'LRD',
    decimals: '2',
    countryName: 'Liberia',
    countryCode: 'LR',
    countryFlag: '🇱🇷',
  },
  {
    name: 'Libyan Dinar',
    code: 'LYD',
    decimals: '3',
    countryName: 'Libya',
    countryCode: 'LY',
    countryFlag: '🇱🇾',
  },
  {
    name: 'Swiss Franc',
    code: 'CHF',
    decimals: '2',
    countryName: 'Switzerland',
    countryCode: 'CH',
    countryFlag: '🇨🇭',
  },
  {
    name: 'Pataca',
    code: 'MOP',
    decimals: '2',
    countryName: 'Macau',
    countryCode: 'MO',
    countryFlag: '🇲🇴',
  },
  {
    name: 'Denar',
    code: 'MKD',
    decimals: '2',
    countryName: 'North Macedonia',
    countryCode: 'MK',
    countryFlag: '🇲🇰',
  },
  {
    name: 'Malagasy Ariary',
    code: 'MGA',
    decimals: '2',
    countryName: 'Madagascar',
    countryCode: 'MG',
    countryFlag: '🇲🇬',
  },
  {
    name: 'Malawi Kwacha',
    code: 'MWK',
    decimals: '2',
    countryName: 'Malawi',
    countryCode: 'MW',
    countryFlag: '🇲🇼',
  },
  {
    name: 'Malaysian Ringgit',
    code: 'MYR',
    decimals: '2',
    countryName: 'Malaysia',
    countryCode: 'MY',
    countryFlag: '🇲🇾',
  },
  {
    name: 'Rufiyaa',
    code: 'MVR',
    decimals: '2',
    countryName: 'Maldives',
    countryCode: 'MV',
    countryFlag: '🇲🇻',
  },
  {
    name: 'Ouguiya',
    code: 'MRU',
    decimals: '2',
    countryName: 'Mauritania',
    countryCode: 'MR',
    countryFlag: '🇲🇷',
  },
  {
    name: 'Mauritius Rupee',
    code: 'MUR',
    decimals: '2',
    countryName: 'Mauritius',
    countryCode: 'MU',
    countryFlag: '🇲🇺',
  },
  {
    name: 'ADB Unit of Account',
    code: 'XUA',
    decimals: '0',
    countryName: 'African Development Bank',
    countryCode: 'XU',
    countryFlag: '🌍',
  },
  {
    name: 'Mexican Peso',
    code: 'MXN',
    decimals: '2',
    countryName: 'Mexico',
    countryCode: 'MX',
    countryFlag: '🇲🇽',
  },
  {
    name: 'Mexican Unidad de Inversion (UDI)',
    code: 'MXV',
    decimals: '2',
    countryName: 'Mexico',
    countryCode: 'MX',
    countryFlag: '🇲🇽',
  },
  {
    name: 'Moldovan Leu',
    code: 'MDL',
    decimals: '2',
    countryName: 'Moldova',
    countryCode: 'MD',
    countryFlag: '🇲🇩',
  },
  {
    name: 'Tugrik',
    code: 'MNT',
    decimals: '2',
    countryName: 'Mongolia',
    countryCode: 'MN',
    countryFlag: '🇲🇳',
  },
  {
    name: 'Moroccan Dirham',
    code: 'MAD',
    decimals: '2',
    countryName: 'Morocco',
    countryCode: 'MA',
    countryFlag: '🇲🇦',
  },
  {
    name: 'Mozambique Metical',
    code: 'MZN',
    decimals: '2',
    countryName: 'Mozambique',
    countryCode: 'MZ',
    countryFlag: '🇲🇿',
  },
  {
    name: 'Kyat',
    code: 'MMK',
    decimals: '2',
    countryName: 'Myanmar',
    countryCode: 'MM',
    countryFlag: '🇲🇲',
  },
  {
    name: 'Namibia Dollar',
    code: 'NAD',
    decimals: '2',
    countryName: 'Namibia',
    countryCode: 'NA',
    countryFlag: '🇳🇦',
  },
  {
    name: 'Nepalese Rupee',
    code: 'NPR',
    decimals: '2',
    countryName: 'Nepal',
    countryCode: 'NP',
    countryFlag: '🇳🇵',
  },
  {
    name: 'Cordoba Oro',
    code: 'NIO',
    decimals: '2',
    countryName: 'Nicaragua',
    countryCode: 'NI',
    countryFlag: '🇳🇮',
  },
  {
    name: 'Naira',
    code: 'NGN',
    decimals: '2',
    countryName: 'Nigeria',
    countryCode: 'NG',
    countryFlag: '🇳🇬',
  },
  {
    name: 'Rial Omani',
    code: 'OMR',
    decimals: '3',
    countryName: 'Oman',
    countryCode: 'OM',
    countryFlag: '🇴🇲',
  },
  {
    name: 'Pakistan Rupee',
    code: 'PKR',
    decimals: '2',
    countryName: 'Pakistan',
    countryCode: 'PK',
    countryFlag: '🇵🇰',
  },
  {
    name: 'Balboa',
    code: 'PAB',
    decimals: '2',
    countryName: 'Panama',
    countryCode: 'PA',
    countryFlag: '🇵🇦',
  },
  {
    name: 'Kina',
    code: 'PGK',
    decimals: '2',
    countryName: 'Papua New Guinea',
    countryCode: 'PG',
    countryFlag: '🇵🇬',
  },
  {
    name: 'Guarani',
    code: 'PYG',
    decimals: '0',
    countryName: 'Paraguay',
    countryCode: 'PY',
    countryFlag: '🇵🇾',
  },
  {
    name: 'Sol',
    code: 'PEN',
    decimals: '2',
    countryName: 'Peru',
    countryCode: 'PE',
    countryFlag: '🇵🇪',
  },
  {
    name: 'Philippine Peso',
    code: 'PHP',
    decimals: '2',
    countryName: 'Philippines',
    countryCode: 'PH',
    countryFlag: '🇵🇭',
  },
  {
    name: 'Zloty',
    code: 'PLN',
    decimals: '2',
    countryName: 'Poland',
    countryCode: 'PL',
    countryFlag: '🇵🇱',
  },
  {
    name: 'Qatari Rial',
    code: 'QAR',
    decimals: '2',
    countryName: 'Qatar',
    countryCode: 'QA',
    countryFlag: '🇶🇦',
  },
  {
    name: 'Romanian Leu',
    code: 'RON',
    decimals: '2',
    countryName: 'Romania',
    countryCode: 'RO',
    countryFlag: '🇷🇴',
  },
  {
    name: 'Russian Ruble',
    code: 'RUB',
    decimals: '2',
    countryName: 'Russia',
    countryCode: 'RU',
    countryFlag: '🇷🇺',
  },
  {
    name: 'Rwanda Franc',
    code: 'RWF',
    decimals: '0',
    countryName: 'Rwanda',
    countryCode: 'RW',
    countryFlag: '🇷🇼',
  },
  {
    name: 'Saint Helena Pound',
    code: 'SHP',
    decimals: '2',
    countryName: 'Saint Helena',
    countryCode: 'SH',
    countryFlag: '🇸🇭',
  },
  {
    name: 'Tala',
    code: 'WST',
    decimals: '2',
    countryName: 'Samoa',
    countryCode: 'WS',
    countryFlag: '🇼🇸',
  },
  {
    name: 'Dobra',
    code: 'STN',
    decimals: '2',
    countryName: 'São Tomé and Príncipe',
    countryCode: 'ST',
    countryFlag: '🇸🇹',
  },
  {
    name: 'Saudi Riyal',
    code: 'SAR',
    decimals: '2',
    countryName: 'Saudi Arabia',
    countryCode: 'SA',
    countryFlag: '🇸🇦',
  },
  {
    name: 'Serbian Dinar',
    code: 'RSD',
    decimals: '2',
    countryName: 'Serbia',
    countryCode: 'RS',
    countryFlag: '🇷🇸',
  },
  {
    name: 'Seychelles Rupee',
    code: 'SCR',
    decimals: '2',
    countryName: 'Seychelles',
    countryCode: 'SC',
    countryFlag: '🇸🇨',
  },
  {
    name: 'Leone',
    code: 'SLE',
    decimals: '2',
    countryName: 'Sierra Leone',
    countryCode: 'SL',
    countryFlag: '🇸🇱',
  },
  {
    name: 'Singapore Dollar',
    code: 'SGD',
    decimals: '2',
    countryName: 'Singapore',
    countryCode: 'SG',
    countryFlag: '🇸🇬',
  },
  {
    name: 'Sucre',
    code: 'XSU',
    decimals: '0',
    countryName: 'SUCRE',
    countryCode: 'XS',
    countryFlag: '🌎',
  },
  {
    name: 'Solomon Islands Dollar',
    code: 'SBD',
    decimals: '2',
    countryName: 'Solomon Islands',
    countryCode: 'SB',
    countryFlag: '🇸🇧',
  },
  {
    name: 'Somali Shilling',
    code: 'SOS',
    decimals: '2',
    countryName: 'Somalia',
    countryCode: 'SO',
    countryFlag: '🇸🇴',
  },
  {
    name: 'South Sudanese Pound',
    code: 'SSP',
    decimals: '2',
    countryName: 'South Sudan',
    countryCode: 'SS',
    countryFlag: '🇸🇸',
  },
  {
    name: 'Sri Lanka Rupee',
    code: 'LKR',
    decimals: '2',
    countryName: 'Sri Lanka',
    countryCode: 'LK',
    countryFlag: '🇱🇰',
  },
  {
    name: 'Sudanese Pound',
    code: 'SDG',
    decimals: '2',
    countryName: 'Sudan',
    countryCode: 'SD',
    countryFlag: '🇸🇩',
  },
  {
    name: 'Surinam Dollar',
    code: 'SRD',
    decimals: '2',
    countryName: 'Suriname',
    countryCode: 'SR',
    countryFlag: '🇸🇷',
  },
  {
    name: 'Swedish Krona',
    code: 'SEK',
    decimals: '2',
    countryName: 'Sweden',
    countryCode: 'SE',
    countryFlag: '🇸🇪',
  },
  {
    name: 'WIR Euro',
    code: 'CHE',
    decimals: '2',
    countryName: 'Switzerland',
    countryCode: 'CH',
    countryFlag: '🇨🇭',
  },
  {
    name: 'WIR Franc',
    code: 'CHW',
    decimals: '2',
    countryName: 'Switzerland',
    countryCode: 'CH',
    countryFlag: '🇨🇭',
  },
  {
    name: 'Syrian Pound',
    code: 'SYP',
    decimals: '2',
    countryName: 'Syria',
    countryCode: 'SY',
    countryFlag: '🇸🇾',
  },
  {
    name: 'New Taiwan Dollar',
    code: 'TWD',
    decimals: '2',
    countryName: 'Taiwan',
    countryCode: 'TW',
    countryFlag: '🇹🇼',
  },
  {
    name: 'Somoni',
    code: 'TJS',
    decimals: '2',
    countryName: 'Tajikistan',
    countryCode: 'TJ',
    countryFlag: '🇹🇯',
  },
  {
    name: 'Tanzanian Shilling',
    code: 'TZS',
    decimals: '2',
    countryName: 'Tanzania',
    countryCode: 'TZ',
    countryFlag: '🇹🇿',
  },
  {
    name: 'Baht',
    code: 'THB',
    decimals: '2',
    countryName: 'Thailand',
    countryCode: 'TH',
    countryFlag: '🇹🇭',
  },
  {
    name: "Pa'anga",
    code: 'TOP',
    decimals: '2',
    countryName: 'Tonga',
    countryCode: 'TO',
    countryFlag: '🇹🇴',
  },
  {
    name: 'Trinidad and Tobago Dollar',
    code: 'TTD',
    decimals: '2',
    countryName: 'Trinidad and Tobago',
    countryCode: 'TT',
    countryFlag: '🇹🇹',
  },
  {
    name: 'Tunisian Dinar',
    code: 'TND',
    decimals: '3',
    countryName: 'Tunisia',
    countryCode: 'TN',
    countryFlag: '🇹🇳',
  },
  {
    name: 'Turkish Lira',
    code: 'TRY',
    decimals: '2',
    countryName: 'Turkey',
    countryCode: 'TR',
    countryFlag: '🇹🇷',
  },
  {
    name: 'Turkmenistan New Manat',
    code: 'TMT',
    decimals: '2',
    countryName: 'Turkmenistan',
    countryCode: 'TM',
    countryFlag: '🇹🇲',
  },
  {
    name: 'Uganda Shilling',
    code: 'UGX',
    decimals: '0',
    countryName: 'Uganda',
    countryCode: 'UG',
    countryFlag: '🇺🇬',
  },
  {
    name: 'Hryvnia',
    code: 'UAH',
    decimals: '2',
    countryName: 'Ukraine',
    countryCode: 'UA',
    countryFlag: '🇺🇦',
  },
  {
    name: 'UAE Dirham',
    code: 'AED',
    decimals: '2',
    countryName: 'United Arab Emirates',
    countryCode: 'AE',
    countryFlag: '🇦🇪',
  },
  {
    name: 'US Dollar (Next day)',
    code: 'USN',
    decimals: '2',
    countryName: 'United States',
    countryCode: 'US',
    countryFlag: '🇺🇸',
  },
  {
    name: 'Peso Uruguayo',
    code: 'UYU',
    decimals: '2',
    countryName: 'Uruguay',
    countryCode: 'UY',
    countryFlag: '🇺🇾',
  },
  {
    name: 'Uruguay Peso en Unidades Indexadas (UI)',
    code: 'UYI',
    decimals: '0',
    countryName: 'Uruguay',
    countryCode: 'UY',
    countryFlag: '🇺🇾',
  },
  {
    name: 'Unidad Previsional',
    code: 'UYW',
    decimals: '4',
    countryName: 'Uruguay',
    countryCode: 'UY',
    countryFlag: '🇺🇾',
  },
  {
    name: 'Uzbekistan Sum',
    code: 'UZS',
    decimals: '2',
    countryName: 'Uzbekistan',
    countryCode: 'UZ',
    countryFlag: '🇺🇿',
  },
  {
    name: 'Vatu',
    code: 'VUV',
    decimals: '0',
    countryName: 'Vanuatu',
    countryCode: 'VU',
    countryFlag: '🇻🇺',
  },
  {
    name: 'Bolívar Soberano',
    code: 'VES',
    decimals: '2',
    countryName: 'Venezuela',
    countryCode: 'VE',
    countryFlag: '🇻🇪',
  },
  {
    name: 'Bolívar Soberano',
    code: 'VED',
    decimals: '2',
    countryName: 'Venezuela',
    countryCode: 'VE',
    countryFlag: '🇻🇪',
  },
  {
    name: 'Dong',
    code: 'VND',
    decimals: '0',
    countryName: 'Vietnam',
    countryCode: 'VN',
    countryFlag: '🇻🇳',
  },
  {
    name: 'Yemeni Rial',
    code: 'YER',
    decimals: '2',
    countryName: 'Yemen',
    countryCode: 'YE',
    countryFlag: '🇾🇪',
  },
  {
    name: 'Zambian Kwacha',
    code: 'ZMW',
    decimals: '2',
    countryName: 'Zambia',
    countryCode: 'ZM',
    countryFlag: '🇿🇲',
  },
  {
    name: 'Zimbabwe Gold',
    code: 'ZWG',
    decimals: '2',
    countryName: 'Zimbabwe',
    countryCode: 'ZW',
    countryFlag: '🇿🇼',
  },
];
