name: e2e Test CI

on:
  push:
    branches:
      - main
      - develop
      - prerelease
      - prerelease/**
  pull_request:
    branches:
      - main
      - develop
      - prerelease
      - prerelease/**

permissions:
  contents: read # to fetch code (actions/checkout)

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: next-8

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: pnpm install
        run: pnpm install

      - name: Setup turbo cache
        env:
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_API: ${{ secrets.TURBO_API }}
        run: node scripts/setupTurboCache.js

      - name: Update versions
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: pnpm ci:version

      - name: Prebuild config
        env:
          APP_NAME: '@cypherock/cysync-desktop'
          CHANNEL: 'ci'
          DO_UPDATE_APP_VERSION: 'true'
        run: node scripts/prebuild.js

      - name: Run tests
        run: pnpm test

      - name: Run end to end tests
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pnpm e2e

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: |
            apps/desktop/playwright-report/
            apps/desktop/test-results/
            apps/desktop/screenshots/
            apps/desktop/videos/
          retention-days: 30
