name: Version

on:
  push:
    branches:
      - main

env:
  CI: true
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: next-8

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: pnpm install
        run: pnpm install

      - name: Setup turbo cache
        env:
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_API: ${{ secrets.TURBO_API }}
        run: node scripts/setupTurboCache.js

      - name: Run build
        run: pnpm build

      - name: create and publish versions
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: echo "Skip publishing packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
